/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#c59300',
        'on-secondary-fixed': '#261a00',
        'primary-fixed-dim': '#ffb4aa',
        'on-tertiary-fixed': '#001b3c',
        'tertiary-fixed-dim': '#a7c8ff',
        'on-tertiary-container': '#f8f9ff',
        'primary-fixed': '#ffdad5',
        'tertiary-container': '#0072d7',
        'surface': '#200e0c',
        'surface-container-highest': '#462f2c',
        'on-tertiary': '#003061',
        'surface-tint': '#ffb4aa',
        'inverse-surface': '#ffdad5',
        'secondary-fixed-dim': '#f6be39',
        'on-secondary': '#402d00',
        'tertiary': '#a7c8ff',
        'on-surface-variant': '#e9bcb6',
        'surface-variant': '#462f2c',
        'on-secondary-container': '#433000',
        'on-primary-fixed-variant': '#930007',
        'on-background': '#ffdad5',
        'on-primary-container': '#fff7f6',
        'error': '#ffb4ab',
        'primary': '#ffb4aa',
        'background': '#200e0c',
        'outline': '#af8782',
        'surface-dim': '#200e0c',
        'on-tertiary-fixed-variant': '#004689',
        'surface-container-high': '#3a2522',
        'surface-container': '#2e1a18',
        'surface-container-lowest': '#1a0908',
        'on-error-container': '#ffdad6',
        'surface-bright': '#4a3330',
        'gold': '#D4A017',
        'canvas': '#0A0A0A',
        'card': '#141414',
        'primary-container': '#E50914',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        card: '12px',
      },
      spacing: {
        lg: '40px',
        xl: '64px',
        md: '24px',
        gutter: '16px',
        'margin-desktop': '48px',
        xs: '4px',
        base: '8px',
        'margin-mobile': '20px',
        sm: '12px',
      },
      fontFamily: {
        'display-xl': ['Poppins', 'sans-serif'],
        'headline-lg': ['Poppins', 'sans-serif'],
        'body-lg': ['Poppins', 'sans-serif'],
        'label-bold': ['Poppins', 'sans-serif'],
        'label-sm': ['Poppins', 'sans-serif'],
        'headline-md': ['Poppins', 'sans-serif'],
        'body-md': ['Poppins', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
